// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: icc/agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerAction_Kind int32

const (
	ContainerAction_KIND_UNSPECIFIED ContainerAction_Kind = 0
	ContainerAction_KIND_START       ContainerAction_Kind = 1
	ContainerAction_KIND_STOP        ContainerAction_Kind = 2
	ContainerAction_KIND_RESTART     ContainerAction_Kind = 3
)

// Enum value maps for ContainerAction_Kind.
var (
	ContainerAction_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_START",
		2: "KIND_STOP",
		3: "KIND_RESTART",
	}
	ContainerAction_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_START":       1,
		"KIND_STOP":        2,
		"KIND_RESTART":     3,
	}
)

func (x ContainerAction_Kind) Enum() *ContainerAction_Kind {
	p := new(ContainerAction_Kind)
	*p = x
	return p
}

func (x ContainerAction_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContainerAction_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_icc_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (ContainerAction_Kind) Type() protoreflect.EnumType {
	return &file_icc_agent_v1_agent_proto_enumTypes[0]
}

func (x ContainerAction_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContainerAction_Kind.Descriptor instead.
func (ContainerAction_Kind) EnumDescriptor() ([]byte, []int) {
	return file_icc_agent_v1_agent_proto_rawDescGZIP(), []int{13, 0}
}

type GetCenterInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCenterInfoRequest) Reset() {
	*x = GetCenterInfoRequest{}
	mi := &file_icc_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCenterInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCenterInfoRequest) ProtoMessage() {}

func (x *GetCenterInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCenterInfoRequest.ProtoReflect.Descriptor instead.
func (*GetCenterInfoRequest) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type GetCenterInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaCertPem     string                 `protobuf:"bytes,1,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCenterInfoResponse) Reset() {
	*x = GetCenterInfoResponse{}
	mi := &file_icc_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCenterInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCenterInfoResponse) ProtoMessage() {}

func (x *GetCenterInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCenterInfoResponse.ProtoReflect.Descriptor instead.
func (*GetCenterInfoResponse) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GetCenterInfoResponse) GetCaCertPem() string {
	if x != nil {
		return x.CaCertPem
	}
	return ""
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Одноразовый токен регистрации, выданный в интерфейсе центра.
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// PKCS#10 CSR в PEM. Закрытый ключ не покидает сервер.
	CsrPem        string    `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	Host          *HostInfo `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	AgentVersion  string    `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_icc_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *RegisterRequest) GetHost() *HostInfo {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type RegisterResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Клиентский сертификат агента в PEM.
	ClientCertPem string `protobuf:"bytes,2,opt,name=client_cert_pem,json=clientCertPem,proto3" json:"client_cert_pem,omitempty"`
	// Сертификат CA центра, которым агент проверяет сервер.
	CaCertPem     string                 `protobuf:"bytes,3,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	CertExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=cert_expires_at,json=certExpiresAt,proto3" json:"cert_expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_icc_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetClientCertPem() string {
	if x != nil {
		return x.ClientCertPem
	}
	return ""
}

func (x *RegisterResponse) GetCaCertPem() string {
	if x != nil {
		return x.CaCertPem
	}
	return ""
}

func (x *RegisterResponse) GetCertExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CertExpiresAt
	}
	return nil
}

type ConnectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Монотонный номер сообщения в рамках соединения; используется в Ack.
	Seq    uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	SentAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConnectRequest_Hello
	//	*ConnectRequest_Heartbeat
	//	*ConnectRequest_Inventory
	//	*ConnectRequest_Metrics
	//	*ConnectRequest_Logs
	//	*ConnectRequest_Change
	//	*ConnectRequest_Runtime
	//	*ConnectRequest_CommandResult
	Payload       isConnectRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_icc_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ConnectRequest) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *ConnectRequest) GetPayload() isConnectRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConnectRequest) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*ConnectRequest_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ConnectRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ConnectRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ConnectRequest) GetInventory() *InventorySnapshot {
	if x != nil {
		if x, ok := x.Payload.(*ConnectRequest_Inventory); ok {
			return x.Inventory
		}
	}
	return nil
}

func (x *ConnectRequest) GetMetrics() *MetricBatch {
	if x != nil {
		if x, ok := x.Payload.(*ConnectRequest_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *ConnectRequest) GetLogs() *LogBatch {
	if x != nil {
		if x, ok := x.Payload.(*ConnectRequest_Logs); ok {
			return x.Logs
		}
	}
	return nil
}

func (x *ConnectRequest) GetChange() *ChangeEvent {
	if x != nil {
		if x, ok := x.Payload.(*ConnectRequest_Change); ok {
			return x.Change
		}
	}
	return nil
}

func (x *ConnectRequest) GetRuntime() *RuntimeEvent {
	if x != nil {
		if x, ok := x.Payload.(*ConnectRequest_Runtime); ok {
			return x.Runtime
		}
	}
	return nil
}

func (x *ConnectRequest) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Payload.(*ConnectRequest_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

type isConnectRequest_Payload interface {
	isConnectRequest_Payload()
}

type ConnectRequest_Hello struct {
	Hello *Hello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type ConnectRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type ConnectRequest_Inventory struct {
	Inventory *InventorySnapshot `protobuf:"bytes,12,opt,name=inventory,proto3,oneof"`
}

type ConnectRequest_Metrics struct {
	Metrics *MetricBatch `protobuf:"bytes,13,opt,name=metrics,proto3,oneof"`
}

type ConnectRequest_Logs struct {
	Logs *LogBatch `protobuf:"bytes,14,opt,name=logs,proto3,oneof"`
}

type ConnectRequest_Change struct {
	Change *ChangeEvent `protobuf:"bytes,15,opt,name=change,proto3,oneof"`
}

type ConnectRequest_Runtime struct {
	Runtime *RuntimeEvent `protobuf:"bytes,16,opt,name=runtime,proto3,oneof"`
}

type ConnectRequest_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,17,opt,name=command_result,json=commandResult,proto3,oneof"`
}

func (*ConnectRequest_Hello) isConnectRequest_Payload() {}

func (*ConnectRequest_Heartbeat) isConnectRequest_Payload() {}

func (*ConnectRequest_Inventory) isConnectRequest_Payload() {}

func (*ConnectRequest_Metrics) isConnectRequest_Payload() {}

func (*ConnectRequest_Logs) isConnectRequest_Payload() {}

func (*ConnectRequest_Change) isConnectRequest_Payload() {}

func (*ConnectRequest_Runtime) isConnectRequest_Payload() {}

func (*ConnectRequest_CommandResult) isConnectRequest_Payload() {}

type Hello struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AgentId      string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentVersion string                 `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Host         *HostInfo              `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	// Последний seq, подтверждённый центром в прошлой сессии: агент дошлёт
	// буферизованные на диске сообщения после него.
	LastAckedSeq  uint64 `protobuf:"varint,4,opt,name=last_acked_seq,json=lastAckedSeq,proto3" json:"last_acked_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_icc_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Hello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetHost() *HostInfo {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Hello) GetLastAckedSeq() uint64 {
	if x != nil {
		return x.LastAckedSeq
	}
	return 0
}

type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Сообщений в дисковом буфере, ещё не подтверждённых центром.
	BufferedMessages uint64  `protobuf:"varint,1,opt,name=buffered_messages,json=bufferedMessages,proto3" json:"buffered_messages,omitempty"`
	AgentCpuPercent  float64 `protobuf:"fixed64,2,opt,name=agent_cpu_percent,json=agentCpuPercent,proto3" json:"agent_cpu_percent,omitempty"`
	AgentRssBytes    uint64  `protobuf:"varint,3,opt,name=agent_rss_bytes,json=agentRssBytes,proto3" json:"agent_rss_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_icc_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Heartbeat) GetBufferedMessages() uint64 {
	if x != nil {
		return x.BufferedMessages
	}
	return 0
}

func (x *Heartbeat) GetAgentCpuPercent() float64 {
	if x != nil {
		return x.AgentCpuPercent
	}
	return 0
}

func (x *Heartbeat) GetAgentRssBytes() uint64 {
	if x != nil {
		return x.AgentRssBytes
	}
	return 0
}

// Результат выполнения команды центра.
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_icc_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type ConnectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConnectResponse_HelloAck
	//	*ConnectResponse_Ack
	//	*ConnectResponse_Command
	Payload       isConnectResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_icc_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ConnectResponse) GetPayload() isConnectResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConnectResponse) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Payload.(*ConnectResponse_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ConnectResponse) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*ConnectResponse_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ConnectResponse) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Payload.(*ConnectResponse_Command); ok {
			return x.Command
		}
	}
	return nil
}

type isConnectResponse_Payload interface {
	isConnectResponse_Payload()
}

type ConnectResponse_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,10,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ConnectResponse_Ack struct {
	Ack *Ack `protobuf:"bytes,11,opt,name=ack,proto3,oneof"`
}

type ConnectResponse_Command struct {
	Command *Command `protobuf:"bytes,12,opt,name=command,proto3,oneof"`
}

func (*ConnectResponse_HelloAck) isConnectResponse_Payload() {}

func (*ConnectResponse_Ack) isConnectResponse_Payload() {}

func (*ConnectResponse_Command) isConnectResponse_Payload() {}

type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *AgentConfig           `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_icc_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *HelloAck) GetConfig() *AgentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Настройки сбора, которые центр задаёт агенту.
type AgentConfig struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatIntervalSeconds uint32                 `protobuf:"varint,1,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	MetricsIntervalSeconds   uint32                 `protobuf:"varint,2,opt,name=metrics_interval_seconds,json=metricsIntervalSeconds,proto3" json:"metrics_interval_seconds,omitempty"`
	InventoryIntervalSeconds uint32                 `protobuf:"varint,3,opt,name=inventory_interval_seconds,json=inventoryIntervalSeconds,proto3" json:"inventory_interval_seconds,omitempty"`
	// Максимальная длина строки лога; длиннее — обрезается.
	MaxLogLineBytes uint32 `protobuf:"varint,4,opt,name=max_log_line_bytes,json=maxLogLineBytes,proto3" json:"max_log_line_bytes,omitempty"`
	// Glob-пути к дополнительным файлам настроек, изменения которых отслеживать
	// (compose-файлы и .env проектов отслеживаются всегда).
	WatchedConfigGlobs []string `protobuf:"bytes,5,rep,name=watched_config_globs,json=watchedConfigGlobs,proto3" json:"watched_config_globs,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentConfig) Reset() {
	*x = AgentConfig{}
	mi := &file_icc_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentConfig) ProtoMessage() {}

func (x *AgentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentConfig.ProtoReflect.Descriptor instead.
func (*AgentConfig) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *AgentConfig) GetHeartbeatIntervalSeconds() uint32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetMetricsIntervalSeconds() uint32 {
	if x != nil {
		return x.MetricsIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetInventoryIntervalSeconds() uint32 {
	if x != nil {
		return x.InventoryIntervalSeconds
	}
	return 0
}

func (x *AgentConfig) GetMaxLogLineBytes() uint32 {
	if x != nil {
		return x.MaxLogLineBytes
	}
	return 0
}

func (x *AgentConfig) GetWatchedConfigGlobs() []string {
	if x != nil {
		return x.WatchedConfigGlobs
	}
	return nil
}

// Подтверждение приёма: агент может удалить из буфера всё до seq включительно.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_icc_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *Ack) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// Команда центра. Подписывается ключом центра (Ed25519) и имеет срок
// действия; агент отбрасывает просроченные и повторные команды и сверяет
// каждую с локальной политикой перед выполнением.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Ключ идемпотентности: повтор с тем же ключом не выполняется дважды.
	IdempotencyKey string `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Кто инициировал (пользователь или система) — для аудита на стороне агента.
	Actor string `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	// Право, которое проверил центр, например "container.restart".
	Permission string                 `protobuf:"bytes,4,opt,name=permission,proto3" json:"permission,omitempty"`
	IssuedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Подпись Ed25519 над каноническим сериализованным Command с пустым signature.
	Signature []byte `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*Command_ContainerAction
	Action        isCommand_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_icc_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Command) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Command) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *Command) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *Command) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Command) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Command) GetAction() isCommand_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Command) GetContainerAction() *ContainerAction {
	if x != nil {
		if x, ok := x.Action.(*Command_ContainerAction); ok {
			return x.ContainerAction
		}
	}
	return nil
}

type isCommand_Action interface {
	isCommand_Action()
}

type Command_ContainerAction struct {
	ContainerAction *ContainerAction `protobuf:"bytes,20,opt,name=container_action,json=containerAction,proto3,oneof"`
}

func (*Command_ContainerAction) isCommand_Action() {}

type ContainerAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ContainerAction_Kind   `protobuf:"varint,1,opt,name=kind,proto3,enum=icc.agent.v1.ContainerAction_Kind" json:"kind,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerAction) Reset() {
	*x = ContainerAction{}
	mi := &file_icc_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerAction) ProtoMessage() {}

func (x *ContainerAction) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerAction.ProtoReflect.Descriptor instead.
func (*ContainerAction) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ContainerAction) GetKind() ContainerAction_Kind {
	if x != nil {
		return x.Kind
	}
	return ContainerAction_KIND_UNSPECIFIED
}

func (x *ContainerAction) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

var File_icc_agent_v1_agent_proto protoreflect.FileDescriptor

const file_icc_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x18icc/agent/v1/agent.proto\x12\ficc.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aicc/agent/v1/changes.proto\x1a\x1cicc/agent/v1/inventory.proto\x1a\x1cicc/agent/v1/telemetry.proto\"\x16\n" +
	"\x14GetCenterInfoRequest\"7\n" +
	"\x15GetCenterInfoResponse\x12\x1e\n" +
	"\vca_cert_pem\x18\x01 \x01(\tR\tcaCertPem\"\x91\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\tR\x06csrPem\x12*\n" +
	"\x04host\x18\x03 \x01(\v2\x16.icc.agent.v1.HostInfoR\x04host\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\"\xb9\x01\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12&\n" +
	"\x0fclient_cert_pem\x18\x02 \x01(\tR\rclientCertPem\x12\x1e\n" +
	"\vca_cert_pem\x18\x03 \x01(\tR\tcaCertPem\x12B\n" +
	"\x0fcert_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rcertExpiresAt\"\xa1\x04\n" +
	"\x0eConnectRequest\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12+\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x13.icc.agent.v1.HelloH\x00R\x05hello\x127\n" +
	"\theartbeat\x18\v \x01(\v2\x17.icc.agent.v1.HeartbeatH\x00R\theartbeat\x12?\n" +
	"\tinventory\x18\f \x01(\v2\x1f.icc.agent.v1.InventorySnapshotH\x00R\tinventory\x125\n" +
	"\ametrics\x18\r \x01(\v2\x19.icc.agent.v1.MetricBatchH\x00R\ametrics\x12,\n" +
	"\x04logs\x18\x0e \x01(\v2\x16.icc.agent.v1.LogBatchH\x00R\x04logs\x123\n" +
	"\x06change\x18\x0f \x01(\v2\x19.icc.agent.v1.ChangeEventH\x00R\x06change\x126\n" +
	"\aruntime\x18\x10 \x01(\v2\x1a.icc.agent.v1.RuntimeEventH\x00R\aruntime\x12D\n" +
	"\x0ecommand_result\x18\x11 \x01(\v2\x1b.icc.agent.v1.CommandResultH\x00R\rcommandResultB\t\n" +
	"\apayload\"\x99\x01\n" +
	"\x05Hello\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12*\n" +
	"\x04host\x18\x03 \x01(\v2\x16.icc.agent.v1.HostInfoR\x04host\x12$\n" +
	"\x0elast_acked_seq\x18\x04 \x01(\x04R\flastAckedSeq\"\x8c\x01\n" +
	"\tHeartbeat\x12+\n" +
	"\x11buffered_messages\x18\x01 \x01(\x04R\x10bufferedMessages\x12*\n" +
	"\x11agent_cpu_percent\x18\x02 \x01(\x01R\x0fagentCpuPercent\x12&\n" +
	"\x0fagent_rss_bytes\x18\x03 \x01(\x04R\ragentRssBytes\"v\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output\"\xad\x01\n" +
	"\x0fConnectResponse\x125\n" +
	"\thello_ack\x18\n" +
	" \x01(\v2\x16.icc.agent.v1.HelloAckH\x00R\bhelloAck\x12%\n" +
	"\x03ack\x18\v \x01(\v2\x11.icc.agent.v1.AckH\x00R\x03ack\x121\n" +
	"\acommand\x18\f \x01(\v2\x15.icc.agent.v1.CommandH\x00R\acommandB\t\n" +
	"\apayload\"=\n" +
	"\bHelloAck\x121\n" +
	"\x06config\x18\x01 \x01(\v2\x19.icc.agent.v1.AgentConfigR\x06config\"\xa2\x02\n" +
	"\vAgentConfig\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x01 \x01(\rR\x18heartbeatIntervalSeconds\x128\n" +
	"\x18metrics_interval_seconds\x18\x02 \x01(\rR\x16metricsIntervalSeconds\x12<\n" +
	"\x1ainventory_interval_seconds\x18\x03 \x01(\rR\x18inventoryIntervalSeconds\x12+\n" +
	"\x12max_log_line_bytes\x18\x04 \x01(\rR\x0fmaxLogLineBytes\x120\n" +
	"\x14watched_config_globs\x18\x05 \x03(\tR\x12watchedConfigGlobs\"\x17\n" +
	"\x03Ack\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\"\xe0\x02\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x1e\n" +
	"\n" +
	"permission\x18\x04 \x01(\tR\n" +
	"permission\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\x12J\n" +
	"\x10container_action\x18\x14 \x01(\v2\x1d.icc.agent.v1.ContainerActionH\x00R\x0fcontainerActionB\b\n" +
	"\x06action\"\xbb\x01\n" +
	"\x0fContainerAction\x126\n" +
	"\x04kind\x18\x01 \x01(\x0e2\".icc.agent.v1.ContainerAction.KindR\x04kind\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\"M\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"KIND_START\x10\x01\x12\r\n" +
	"\tKIND_STOP\x10\x02\x12\x10\n" +
	"\fKIND_RESTART\x10\x032\xff\x01\n" +
	"\fAgentService\x12X\n" +
	"\rGetCenterInfo\x12\".icc.agent.v1.GetCenterInfoRequest\x1a#.icc.agent.v1.GetCenterInfoResponse\x12I\n" +
	"\bRegister\x12\x1d.icc.agent.v1.RegisterRequest\x1a\x1e.icc.agent.v1.RegisterResponse\x12J\n" +
	"\aConnect\x12\x1c.icc.agent.v1.ConnectRequest\x1a\x1d.icc.agent.v1.ConnectResponse(\x010\x01B\x9c\x01\n" +
	"\x10com.icc.agent.v1B\n" +
	"AgentProtoP\x01Z*icc/agent/internal/pb/icc/agent/v1;agentv1\xa2\x02\x03IAX\xaa\x02\fIcc.Agent.V1\xca\x02\fIcc\\Agent\\V1\xe2\x02\x18Icc\\Agent\\V1\\GPBMetadata\xea\x02\x0eIcc::Agent::V1b\x06proto3"

var (
	file_icc_agent_v1_agent_proto_rawDescOnce sync.Once
	file_icc_agent_v1_agent_proto_rawDescData []byte
)

func file_icc_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_icc_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_icc_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_icc_agent_v1_agent_proto_rawDesc), len(file_icc_agent_v1_agent_proto_rawDesc)))
	})
	return file_icc_agent_v1_agent_proto_rawDescData
}

var file_icc_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_icc_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_icc_agent_v1_agent_proto_goTypes = []any{
	(ContainerAction_Kind)(0),     // 0: icc.agent.v1.ContainerAction.Kind
	(*GetCenterInfoRequest)(nil),  // 1: icc.agent.v1.GetCenterInfoRequest
	(*GetCenterInfoResponse)(nil), // 2: icc.agent.v1.GetCenterInfoResponse
	(*RegisterRequest)(nil),       // 3: icc.agent.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 4: icc.agent.v1.RegisterResponse
	(*ConnectRequest)(nil),        // 5: icc.agent.v1.ConnectRequest
	(*Hello)(nil),                 // 6: icc.agent.v1.Hello
	(*Heartbeat)(nil),             // 7: icc.agent.v1.Heartbeat
	(*CommandResult)(nil),         // 8: icc.agent.v1.CommandResult
	(*ConnectResponse)(nil),       // 9: icc.agent.v1.ConnectResponse
	(*HelloAck)(nil),              // 10: icc.agent.v1.HelloAck
	(*AgentConfig)(nil),           // 11: icc.agent.v1.AgentConfig
	(*Ack)(nil),                   // 12: icc.agent.v1.Ack
	(*Command)(nil),               // 13: icc.agent.v1.Command
	(*ContainerAction)(nil),       // 14: icc.agent.v1.ContainerAction
	(*HostInfo)(nil),              // 15: icc.agent.v1.HostInfo
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
	(*InventorySnapshot)(nil),     // 17: icc.agent.v1.InventorySnapshot
	(*MetricBatch)(nil),           // 18: icc.agent.v1.MetricBatch
	(*LogBatch)(nil),              // 19: icc.agent.v1.LogBatch
	(*ChangeEvent)(nil),           // 20: icc.agent.v1.ChangeEvent
	(*RuntimeEvent)(nil),          // 21: icc.agent.v1.RuntimeEvent
}
var file_icc_agent_v1_agent_proto_depIdxs = []int32{
	15, // 0: icc.agent.v1.RegisterRequest.host:type_name -> icc.agent.v1.HostInfo
	16, // 1: icc.agent.v1.RegisterResponse.cert_expires_at:type_name -> google.protobuf.Timestamp
	16, // 2: icc.agent.v1.ConnectRequest.sent_at:type_name -> google.protobuf.Timestamp
	6,  // 3: icc.agent.v1.ConnectRequest.hello:type_name -> icc.agent.v1.Hello
	7,  // 4: icc.agent.v1.ConnectRequest.heartbeat:type_name -> icc.agent.v1.Heartbeat
	17, // 5: icc.agent.v1.ConnectRequest.inventory:type_name -> icc.agent.v1.InventorySnapshot
	18, // 6: icc.agent.v1.ConnectRequest.metrics:type_name -> icc.agent.v1.MetricBatch
	19, // 7: icc.agent.v1.ConnectRequest.logs:type_name -> icc.agent.v1.LogBatch
	20, // 8: icc.agent.v1.ConnectRequest.change:type_name -> icc.agent.v1.ChangeEvent
	21, // 9: icc.agent.v1.ConnectRequest.runtime:type_name -> icc.agent.v1.RuntimeEvent
	8,  // 10: icc.agent.v1.ConnectRequest.command_result:type_name -> icc.agent.v1.CommandResult
	15, // 11: icc.agent.v1.Hello.host:type_name -> icc.agent.v1.HostInfo
	10, // 12: icc.agent.v1.ConnectResponse.hello_ack:type_name -> icc.agent.v1.HelloAck
	12, // 13: icc.agent.v1.ConnectResponse.ack:type_name -> icc.agent.v1.Ack
	13, // 14: icc.agent.v1.ConnectResponse.command:type_name -> icc.agent.v1.Command
	11, // 15: icc.agent.v1.HelloAck.config:type_name -> icc.agent.v1.AgentConfig
	16, // 16: icc.agent.v1.Command.issued_at:type_name -> google.protobuf.Timestamp
	16, // 17: icc.agent.v1.Command.expires_at:type_name -> google.protobuf.Timestamp
	14, // 18: icc.agent.v1.Command.container_action:type_name -> icc.agent.v1.ContainerAction
	0,  // 19: icc.agent.v1.ContainerAction.kind:type_name -> icc.agent.v1.ContainerAction.Kind
	1,  // 20: icc.agent.v1.AgentService.GetCenterInfo:input_type -> icc.agent.v1.GetCenterInfoRequest
	3,  // 21: icc.agent.v1.AgentService.Register:input_type -> icc.agent.v1.RegisterRequest
	5,  // 22: icc.agent.v1.AgentService.Connect:input_type -> icc.agent.v1.ConnectRequest
	2,  // 23: icc.agent.v1.AgentService.GetCenterInfo:output_type -> icc.agent.v1.GetCenterInfoResponse
	4,  // 24: icc.agent.v1.AgentService.Register:output_type -> icc.agent.v1.RegisterResponse
	9,  // 25: icc.agent.v1.AgentService.Connect:output_type -> icc.agent.v1.ConnectResponse
	23, // [23:26] is the sub-list for method output_type
	20, // [20:23] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_icc_agent_v1_agent_proto_init() }
func file_icc_agent_v1_agent_proto_init() {
	if File_icc_agent_v1_agent_proto != nil {
		return
	}
	file_icc_agent_v1_changes_proto_init()
	file_icc_agent_v1_inventory_proto_init()
	file_icc_agent_v1_telemetry_proto_init()
	file_icc_agent_v1_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*ConnectRequest_Hello)(nil),
		(*ConnectRequest_Heartbeat)(nil),
		(*ConnectRequest_Inventory)(nil),
		(*ConnectRequest_Metrics)(nil),
		(*ConnectRequest_Logs)(nil),
		(*ConnectRequest_Change)(nil),
		(*ConnectRequest_Runtime)(nil),
		(*ConnectRequest_CommandResult)(nil),
	}
	file_icc_agent_v1_agent_proto_msgTypes[8].OneofWrappers = []any{
		(*ConnectResponse_HelloAck)(nil),
		(*ConnectResponse_Ack)(nil),
		(*ConnectResponse_Command)(nil),
	}
	file_icc_agent_v1_agent_proto_msgTypes[12].OneofWrappers = []any{
		(*Command_ContainerAction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_icc_agent_v1_agent_proto_rawDesc), len(file_icc_agent_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_icc_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_icc_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_icc_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_icc_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_icc_agent_v1_agent_proto = out.File
	file_icc_agent_v1_agent_proto_goTypes = nil
	file_icc_agent_v1_agent_proto_depIdxs = nil
}
