// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: icc/agent/v1/changes.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeKind int32

const (
	ChangeKind_CHANGE_KIND_UNSPECIFIED ChangeKind = 0
	// Контейнер сервиса запущен с другим образом (другой image_id).
	ChangeKind_CHANGE_KIND_IMAGE_CHANGED ChangeKind = 1
	// Контейнер пересоздан (новый id у того же compose-сервиса).
	ChangeKind_CHANGE_KIND_CONTAINER_RECREATED ChangeKind = 2
	// Изменился environment контейнера.
	ChangeKind_CHANGE_KIND_ENV_CHANGED ChangeKind = 3
	// Изменился compose-файл проекта.
	ChangeKind_CHANGE_KIND_COMPOSE_FILE_CHANGED ChangeKind = 4
	// Изменился .env-файл проекта.
	ChangeKind_CHANGE_KIND_ENV_FILE_CHANGED ChangeKind = 5
	// Изменился отслеживаемый файл настроек (appsettings.json и т.п.).
	ChangeKind_CHANGE_KIND_CONFIG_FILE_CHANGED ChangeKind = 6
	// Появился новый контейнер или compose-сервис.
	ChangeKind_CHANGE_KIND_CONTAINER_ADDED ChangeKind = 7
	// Контейнер или compose-сервис удалён.
	ChangeKind_CHANGE_KIND_CONTAINER_REMOVED ChangeKind = 8
	// Изменились лимиты ресурсов контейнера.
	ChangeKind_CHANGE_KIND_LIMITS_CHANGED ChangeKind = 9
)

// Enum value maps for ChangeKind.
var (
	ChangeKind_name = map[int32]string{
		0: "CHANGE_KIND_UNSPECIFIED",
		1: "CHANGE_KIND_IMAGE_CHANGED",
		2: "CHANGE_KIND_CONTAINER_RECREATED",
		3: "CHANGE_KIND_ENV_CHANGED",
		4: "CHANGE_KIND_COMPOSE_FILE_CHANGED",
		5: "CHANGE_KIND_ENV_FILE_CHANGED",
		6: "CHANGE_KIND_CONFIG_FILE_CHANGED",
		7: "CHANGE_KIND_CONTAINER_ADDED",
		8: "CHANGE_KIND_CONTAINER_REMOVED",
		9: "CHANGE_KIND_LIMITS_CHANGED",
	}
	ChangeKind_value = map[string]int32{
		"CHANGE_KIND_UNSPECIFIED":          0,
		"CHANGE_KIND_IMAGE_CHANGED":        1,
		"CHANGE_KIND_CONTAINER_RECREATED":  2,
		"CHANGE_KIND_ENV_CHANGED":          3,
		"CHANGE_KIND_COMPOSE_FILE_CHANGED": 4,
		"CHANGE_KIND_ENV_FILE_CHANGED":     5,
		"CHANGE_KIND_CONFIG_FILE_CHANGED":  6,
		"CHANGE_KIND_CONTAINER_ADDED":      7,
		"CHANGE_KIND_CONTAINER_REMOVED":    8,
		"CHANGE_KIND_LIMITS_CHANGED":       9,
	}
)

func (x ChangeKind) Enum() *ChangeKind {
	p := new(ChangeKind)
	*p = x
	return p
}

func (x ChangeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_icc_agent_v1_changes_proto_enumTypes[0].Descriptor()
}

func (ChangeKind) Type() protoreflect.EnumType {
	return &file_icc_agent_v1_changes_proto_enumTypes[0]
}

func (x ChangeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeKind.Descriptor instead.
func (ChangeKind) EnumDescriptor() ([]byte, []int) {
	return file_icc_agent_v1_changes_proto_rawDescGZIP(), []int{0}
}

type RuntimeEventKind int32

const (
	RuntimeEventKind_RUNTIME_EVENT_KIND_UNSPECIFIED    RuntimeEventKind = 0
	RuntimeEventKind_RUNTIME_EVENT_KIND_STARTED        RuntimeEventKind = 1
	RuntimeEventKind_RUNTIME_EVENT_KIND_STOPPED        RuntimeEventKind = 2
	RuntimeEventKind_RUNTIME_EVENT_KIND_DIED           RuntimeEventKind = 3
	RuntimeEventKind_RUNTIME_EVENT_KIND_OOM_KILLED     RuntimeEventKind = 4
	RuntimeEventKind_RUNTIME_EVENT_KIND_RESTARTED      RuntimeEventKind = 5
	RuntimeEventKind_RUNTIME_EVENT_KIND_HEALTH_CHANGED RuntimeEventKind = 6
)

// Enum value maps for RuntimeEventKind.
var (
	RuntimeEventKind_name = map[int32]string{
		0: "RUNTIME_EVENT_KIND_UNSPECIFIED",
		1: "RUNTIME_EVENT_KIND_STARTED",
		2: "RUNTIME_EVENT_KIND_STOPPED",
		3: "RUNTIME_EVENT_KIND_DIED",
		4: "RUNTIME_EVENT_KIND_OOM_KILLED",
		5: "RUNTIME_EVENT_KIND_RESTARTED",
		6: "RUNTIME_EVENT_KIND_HEALTH_CHANGED",
	}
	RuntimeEventKind_value = map[string]int32{
		"RUNTIME_EVENT_KIND_UNSPECIFIED":    0,
		"RUNTIME_EVENT_KIND_STARTED":        1,
		"RUNTIME_EVENT_KIND_STOPPED":        2,
		"RUNTIME_EVENT_KIND_DIED":           3,
		"RUNTIME_EVENT_KIND_OOM_KILLED":     4,
		"RUNTIME_EVENT_KIND_RESTARTED":      5,
		"RUNTIME_EVENT_KIND_HEALTH_CHANGED": 6,
	}
)

func (x RuntimeEventKind) Enum() *RuntimeEventKind {
	p := new(RuntimeEventKind)
	*p = x
	return p
}

func (x RuntimeEventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeEventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_icc_agent_v1_changes_proto_enumTypes[1].Descriptor()
}

func (RuntimeEventKind) Type() protoreflect.EnumType {
	return &file_icc_agent_v1_changes_proto_enumTypes[1]
}

func (x RuntimeEventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeEventKind.Descriptor instead.
func (RuntimeEventKind) EnumDescriptor() ([]byte, []int) {
	return file_icc_agent_v1_changes_proto_rawDescGZIP(), []int{1}
}

// Изменение конфигурации, обнаруженное агентом. Это главный источник
// признаков «истории изменений» для модели ранжирования первопричин.
type ChangeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID, генерируется агентом; центр по нему отбрасывает дубли.
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DetectedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	Kind       ChangeKind             `protobuf:"varint,3,opt,name=kind,proto3,enum=icc.agent.v1.ChangeKind" json:"kind,omitempty"`
	Target     *ChangeTarget          `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	// Построчные или поключевые различия «было → стало».
	Fields []*FieldChange `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
	// Унифицированный diff для файлов (compose, .env, настройки).
	UnifiedDiff string `protobuf:"bytes,6,opt,name=unified_diff,json=unifiedDiff,proto3" json:"unified_diff,omitempty"`
	// Кто сделал изменение, если агент может это определить
	// (например, пользователь из auditd или "icc" для изменений через центр).
	Actor         string `protobuf:"bytes,7,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEvent) Reset() {
	*x = ChangeEvent{}
	mi := &file_icc_agent_v1_changes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEvent) ProtoMessage() {}

func (x *ChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_changes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEvent.ProtoReflect.Descriptor instead.
func (*ChangeEvent) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_changes_proto_rawDescGZIP(), []int{0}
}

func (x *ChangeEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChangeEvent) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

func (x *ChangeEvent) GetKind() ChangeKind {
	if x != nil {
		return x.Kind
	}
	return ChangeKind_CHANGE_KIND_UNSPECIFIED
}

func (x *ChangeEvent) GetTarget() *ChangeTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ChangeEvent) GetFields() []*FieldChange {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *ChangeEvent) GetUnifiedDiff() string {
	if x != nil {
		return x.UnifiedDiff
	}
	return ""
}

func (x *ChangeEvent) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

type ChangeTarget struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContainerId    string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerName  string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ComposeProject string                 `protobuf:"bytes,3,opt,name=compose_project,json=composeProject,proto3" json:"compose_project,omitempty"`
	ComposeService string                 `protobuf:"bytes,4,opt,name=compose_service,json=composeService,proto3" json:"compose_service,omitempty"`
	// Для файловых изменений — абсолютный путь на хосте.
	FilePath      string `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeTarget) Reset() {
	*x = ChangeTarget{}
	mi := &file_icc_agent_v1_changes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeTarget) ProtoMessage() {}

func (x *ChangeTarget) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_changes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeTarget.ProtoReflect.Descriptor instead.
func (*ChangeTarget) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_changes_proto_rawDescGZIP(), []int{1}
}

func (x *ChangeTarget) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *ChangeTarget) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *ChangeTarget) GetComposeProject() string {
	if x != nil {
		return x.ComposeProject
	}
	return ""
}

func (x *ChangeTarget) GetComposeService() string {
	if x != nil {
		return x.ComposeService
	}
	return ""
}

func (x *ChangeTarget) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type FieldChange struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Key    string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Before string                 `protobuf:"bytes,2,opt,name=before,proto3" json:"before,omitempty"`
	After  string                 `protobuf:"bytes,3,opt,name=after,proto3" json:"after,omitempty"`
	// Значение похоже на секрет и заменено маской; сравниваются только хеши.
	Masked        bool `protobuf:"varint,4,opt,name=masked,proto3" json:"masked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldChange) Reset() {
	*x = FieldChange{}
	mi := &file_icc_agent_v1_changes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldChange) ProtoMessage() {}

func (x *FieldChange) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_changes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldChange.ProtoReflect.Descriptor instead.
func (*FieldChange) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_changes_proto_rawDescGZIP(), []int{2}
}

func (x *FieldChange) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FieldChange) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

func (x *FieldChange) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *FieldChange) GetMasked() bool {
	if x != nil {
		return x.Masked
	}
	return false
}

// Событие жизненного цикла контейнера (не изменение конфигурации).
type RuntimeEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Kind           RuntimeEventKind       `protobuf:"varint,2,opt,name=kind,proto3,enum=icc.agent.v1.RuntimeEventKind" json:"kind,omitempty"`
	ContainerId    string                 `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerName  string                 `protobuf:"bytes,4,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ComposeProject string                 `protobuf:"bytes,5,opt,name=compose_project,json=composeProject,proto3" json:"compose_project,omitempty"`
	ComposeService string                 `protobuf:"bytes,6,opt,name=compose_service,json=composeService,proto3" json:"compose_service,omitempty"`
	// Для DIED.
	ExitCode int32 `protobuf:"varint,7,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Для HEALTH_CHANGED: healthy, unhealthy, starting.
	HealthStatus  string `protobuf:"bytes,8,opt,name=health_status,json=healthStatus,proto3" json:"health_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeEvent) Reset() {
	*x = RuntimeEvent{}
	mi := &file_icc_agent_v1_changes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEvent) ProtoMessage() {}

func (x *RuntimeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_changes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEvent.ProtoReflect.Descriptor instead.
func (*RuntimeEvent) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_changes_proto_rawDescGZIP(), []int{3}
}

func (x *RuntimeEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RuntimeEvent) GetKind() RuntimeEventKind {
	if x != nil {
		return x.Kind
	}
	return RuntimeEventKind_RUNTIME_EVENT_KIND_UNSPECIFIED
}

func (x *RuntimeEvent) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RuntimeEvent) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *RuntimeEvent) GetComposeProject() string {
	if x != nil {
		return x.ComposeProject
	}
	return ""
}

func (x *RuntimeEvent) GetComposeService() string {
	if x != nil {
		return x.ComposeService
	}
	return ""
}

func (x *RuntimeEvent) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RuntimeEvent) GetHealthStatus() string {
	if x != nil {
		return x.HealthStatus
	}
	return ""
}

var File_icc_agent_v1_changes_proto protoreflect.FileDescriptor

const file_icc_agent_v1_changes_proto_rawDesc = "" +
	"\n" +
	"\x1aicc/agent/v1/changes.proto\x12\ficc.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x02\n" +
	"\vChangeEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\vdetected_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\x12,\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x18.icc.agent.v1.ChangeKindR\x04kind\x122\n" +
	"\x06target\x18\x04 \x01(\v2\x1a.icc.agent.v1.ChangeTargetR\x06target\x121\n" +
	"\x06fields\x18\x05 \x03(\v2\x19.icc.agent.v1.FieldChangeR\x06fields\x12!\n" +
	"\funified_diff\x18\x06 \x01(\tR\vunifiedDiff\x12\x14\n" +
	"\x05actor\x18\a \x01(\tR\x05actor\"\xc7\x01\n" +
	"\fChangeTarget\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12'\n" +
	"\x0fcompose_project\x18\x03 \x01(\tR\x0ecomposeProject\x12'\n" +
	"\x0fcompose_service\x18\x04 \x01(\tR\x0ecomposeService\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\"e\n" +
	"\vFieldChange\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06before\x18\x02 \x01(\tR\x06before\x12\x14\n" +
	"\x05after\x18\x03 \x01(\tR\x05after\x12\x16\n" +
	"\x06masked\x18\x04 \x01(\bR\x06masked\"\xda\x02\n" +
	"\fRuntimeEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x122\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1e.icc.agent.v1.RuntimeEventKindR\x04kind\x12!\n" +
	"\fcontainer_id\x18\x03 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x04 \x01(\tR\rcontainerName\x12'\n" +
	"\x0fcompose_project\x18\x05 \x01(\tR\x0ecomposeProject\x12'\n" +
	"\x0fcompose_service\x18\x06 \x01(\tR\x0ecomposeService\x12\x1b\n" +
	"\texit_code\x18\a \x01(\x05R\bexitCode\x12#\n" +
	"\rhealth_status\x18\b \x01(\tR\fhealthStatus*\xdb\x02\n" +
	"\n" +
	"ChangeKind\x12\x1b\n" +
	"\x17CHANGE_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19CHANGE_KIND_IMAGE_CHANGED\x10\x01\x12#\n" +
	"\x1fCHANGE_KIND_CONTAINER_RECREATED\x10\x02\x12\x1b\n" +
	"\x17CHANGE_KIND_ENV_CHANGED\x10\x03\x12$\n" +
	" CHANGE_KIND_COMPOSE_FILE_CHANGED\x10\x04\x12 \n" +
	"\x1cCHANGE_KIND_ENV_FILE_CHANGED\x10\x05\x12#\n" +
	"\x1fCHANGE_KIND_CONFIG_FILE_CHANGED\x10\x06\x12\x1f\n" +
	"\x1bCHANGE_KIND_CONTAINER_ADDED\x10\a\x12!\n" +
	"\x1dCHANGE_KIND_CONTAINER_REMOVED\x10\b\x12\x1e\n" +
	"\x1aCHANGE_KIND_LIMITS_CHANGED\x10\t*\xff\x01\n" +
	"\x10RuntimeEventKind\x12\"\n" +
	"\x1eRUNTIME_EVENT_KIND_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aRUNTIME_EVENT_KIND_STARTED\x10\x01\x12\x1e\n" +
	"\x1aRUNTIME_EVENT_KIND_STOPPED\x10\x02\x12\x1b\n" +
	"\x17RUNTIME_EVENT_KIND_DIED\x10\x03\x12!\n" +
	"\x1dRUNTIME_EVENT_KIND_OOM_KILLED\x10\x04\x12 \n" +
	"\x1cRUNTIME_EVENT_KIND_RESTARTED\x10\x05\x12%\n" +
	"!RUNTIME_EVENT_KIND_HEALTH_CHANGED\x10\x06B\x9e\x01\n" +
	"\x10com.icc.agent.v1B\fChangesProtoP\x01Z*icc/agent/internal/pb/icc/agent/v1;agentv1\xa2\x02\x03IAX\xaa\x02\fIcc.Agent.V1\xca\x02\fIcc\\Agent\\V1\xe2\x02\x18Icc\\Agent\\V1\\GPBMetadata\xea\x02\x0eIcc::Agent::V1b\x06proto3"

var (
	file_icc_agent_v1_changes_proto_rawDescOnce sync.Once
	file_icc_agent_v1_changes_proto_rawDescData []byte
)

func file_icc_agent_v1_changes_proto_rawDescGZIP() []byte {
	file_icc_agent_v1_changes_proto_rawDescOnce.Do(func() {
		file_icc_agent_v1_changes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_icc_agent_v1_changes_proto_rawDesc), len(file_icc_agent_v1_changes_proto_rawDesc)))
	})
	return file_icc_agent_v1_changes_proto_rawDescData
}

var file_icc_agent_v1_changes_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_icc_agent_v1_changes_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_icc_agent_v1_changes_proto_goTypes = []any{
	(ChangeKind)(0),               // 0: icc.agent.v1.ChangeKind
	(RuntimeEventKind)(0),         // 1: icc.agent.v1.RuntimeEventKind
	(*ChangeEvent)(nil),           // 2: icc.agent.v1.ChangeEvent
	(*ChangeTarget)(nil),          // 3: icc.agent.v1.ChangeTarget
	(*FieldChange)(nil),           // 4: icc.agent.v1.FieldChange
	(*RuntimeEvent)(nil),          // 5: icc.agent.v1.RuntimeEvent
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_icc_agent_v1_changes_proto_depIdxs = []int32{
	6, // 0: icc.agent.v1.ChangeEvent.detected_at:type_name -> google.protobuf.Timestamp
	0, // 1: icc.agent.v1.ChangeEvent.kind:type_name -> icc.agent.v1.ChangeKind
	3, // 2: icc.agent.v1.ChangeEvent.target:type_name -> icc.agent.v1.ChangeTarget
	4, // 3: icc.agent.v1.ChangeEvent.fields:type_name -> icc.agent.v1.FieldChange
	6, // 4: icc.agent.v1.RuntimeEvent.timestamp:type_name -> google.protobuf.Timestamp
	1, // 5: icc.agent.v1.RuntimeEvent.kind:type_name -> icc.agent.v1.RuntimeEventKind
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_icc_agent_v1_changes_proto_init() }
func file_icc_agent_v1_changes_proto_init() {
	if File_icc_agent_v1_changes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_icc_agent_v1_changes_proto_rawDesc), len(file_icc_agent_v1_changes_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_icc_agent_v1_changes_proto_goTypes,
		DependencyIndexes: file_icc_agent_v1_changes_proto_depIdxs,
		EnumInfos:         file_icc_agent_v1_changes_proto_enumTypes,
		MessageInfos:      file_icc_agent_v1_changes_proto_msgTypes,
	}.Build()
	File_icc_agent_v1_changes_proto = out.File
	file_icc_agent_v1_changes_proto_goTypes = nil
	file_icc_agent_v1_changes_proto_depIdxs = nil
}
