// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: icc/agent/v1/inventory.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hostname         string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os               string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	KernelVersion    string                 `protobuf:"bytes,3,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	Architecture     string                 `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"`
	CpuCores         uint32                 `protobuf:"varint,5,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryTotalBytes uint64                 `protobuf:"varint,6,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	DockerVersion    string                 `protobuf:"bytes,7,opt,name=docker_version,json=dockerVersion,proto3" json:"docker_version,omitempty"`
	IpAddresses      []string               `protobuf:"bytes,8,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_icc_agent_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *HostInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *HostInfo) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *HostInfo) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *HostInfo) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *HostInfo) GetDockerVersion() string {
	if x != nil {
		return x.DockerVersion
	}
	return ""
}

func (x *HostInfo) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

// Полный снимок того, что работает на хосте. Отправляется при подключении
// и периодически; центр сверяет его с предыдущим.
type InventorySnapshot struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CollectedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	Host            *HostInfo              `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Containers      []*Container           `protobuf:"bytes,3,rep,name=containers,proto3" json:"containers,omitempty"`
	ComposeProjects []*ComposeProject      `protobuf:"bytes,4,rep,name=compose_projects,json=composeProjects,proto3" json:"compose_projects,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InventorySnapshot) Reset() {
	*x = InventorySnapshot{}
	mi := &file_icc_agent_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventorySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventorySnapshot) ProtoMessage() {}

func (x *InventorySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventorySnapshot.ProtoReflect.Descriptor instead.
func (*InventorySnapshot) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *InventorySnapshot) GetCollectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectedAt
	}
	return nil
}

func (x *InventorySnapshot) GetHost() *HostInfo {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *InventorySnapshot) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *InventorySnapshot) GetComposeProjects() []*ComposeProject {
	if x != nil {
		return x.ComposeProjects
	}
	return nil
}

type Container struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Ссылка на образ, как в compose (например, "postgres:17").
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	// Идентификатор образа (sha256:...), по нему видна подмена тега.
	ImageId      string                 `protobuf:"bytes,4,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	State        string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Status       string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	RestartCount uint32                 `protobuf:"varint,9,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	// Пусто, если контейнер не принадлежит compose-проекту.
	ComposeProject string            `protobuf:"bytes,10,opt,name=compose_project,json=composeProject,proto3" json:"compose_project,omitempty"`
	ComposeService string            `protobuf:"bytes,11,opt,name=compose_service,json=composeService,proto3" json:"compose_service,omitempty"`
	Labels         map[string]string `protobuf:"bytes,12,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ports          []*PortBinding    `protobuf:"bytes,13,rep,name=ports,proto3" json:"ports,omitempty"`
	Limits         *ResourceLimits   `protobuf:"bytes,14,opt,name=limits,proto3" json:"limits,omitempty"`
	// Хеш итогового environment контейнера (значения не передаются в снимке).
	EnvHash       string `protobuf:"bytes,15,opt,name=env_hash,json=envHash,proto3" json:"env_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_icc_agent_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *Container) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Container) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Container) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Container) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Container) GetRestartCount() uint32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *Container) GetComposeProject() string {
	if x != nil {
		return x.ComposeProject
	}
	return ""
}

func (x *Container) GetComposeService() string {
	if x != nil {
		return x.ComposeService
	}
	return ""
}

func (x *Container) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Container) GetPorts() []*PortBinding {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Container) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *Container) GetEnvHash() string {
	if x != nil {
		return x.EnvHash
	}
	return ""
}

type PortBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerPort uint32                 `protobuf:"varint,1,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	HostIp        string                 `protobuf:"bytes,3,opt,name=host_ip,json=hostIp,proto3" json:"host_ip,omitempty"`
	HostPort      uint32                 `protobuf:"varint,4,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortBinding) Reset() {
	*x = PortBinding{}
	mi := &file_icc_agent_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortBinding) ProtoMessage() {}

func (x *PortBinding) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortBinding.ProtoReflect.Descriptor instead.
func (*PortBinding) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *PortBinding) GetContainerPort() uint32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *PortBinding) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PortBinding) GetHostIp() string {
	if x != nil {
		return x.HostIp
	}
	return ""
}

func (x *PortBinding) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

type ResourceLimits struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 0 — без ограничения.
	Cpus          float64 `protobuf:"fixed64,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	MemoryBytes   uint64  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_icc_agent_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceLimits) GetCpus() float64 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *ResourceLimits) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type ComposeProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,2,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	ConfigFiles   []string               `protobuf:"bytes,3,rep,name=config_files,json=configFiles,proto3" json:"config_files,omitempty"`
	EnvFiles      []string               `protobuf:"bytes,4,rep,name=env_files,json=envFiles,proto3" json:"env_files,omitempty"`
	Services      []string               `protobuf:"bytes,5,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComposeProject) Reset() {
	*x = ComposeProject{}
	mi := &file_icc_agent_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposeProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeProject) ProtoMessage() {}

func (x *ComposeProject) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeProject.ProtoReflect.Descriptor instead.
func (*ComposeProject) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ComposeProject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComposeProject) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *ComposeProject) GetConfigFiles() []string {
	if x != nil {
		return x.ConfigFiles
	}
	return nil
}

func (x *ComposeProject) GetEnvFiles() []string {
	if x != nil {
		return x.EnvFiles
	}
	return nil
}

func (x *ComposeProject) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

var File_icc_agent_v1_inventory_proto protoreflect.FileDescriptor

const file_icc_agent_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cicc/agent/v1/inventory.proto\x12\ficc.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x02\n" +
	"\bHostInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12%\n" +
	"\x0ekernel_version\x18\x03 \x01(\tR\rkernelVersion\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\x12\x1b\n" +
	"\tcpu_cores\x18\x05 \x01(\rR\bcpuCores\x12,\n" +
	"\x12memory_total_bytes\x18\x06 \x01(\x04R\x10memoryTotalBytes\x12%\n" +
	"\x0edocker_version\x18\a \x01(\tR\rdockerVersion\x12!\n" +
	"\fip_addresses\x18\b \x03(\tR\vipAddresses\"\x80\x02\n" +
	"\x11InventorySnapshot\x12=\n" +
	"\fcollected_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vcollectedAt\x12*\n" +
	"\x04host\x18\x02 \x01(\v2\x16.icc.agent.v1.HostInfoR\x04host\x127\n" +
	"\n" +
	"containers\x18\x03 \x03(\v2\x17.icc.agent.v1.ContainerR\n" +
	"containers\x12G\n" +
	"\x10compose_projects\x18\x04 \x03(\v2\x1c.icc.agent.v1.ComposeProjectR\x0fcomposeProjects\"\xf5\x04\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x19\n" +
	"\bimage_id\x18\x04 \x01(\tR\aimageId\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12#\n" +
	"\rrestart_count\x18\t \x01(\rR\frestartCount\x12'\n" +
	"\x0fcompose_project\x18\n" +
	" \x01(\tR\x0ecomposeProject\x12'\n" +
	"\x0fcompose_service\x18\v \x01(\tR\x0ecomposeService\x12;\n" +
	"\x06labels\x18\f \x03(\v2#.icc.agent.v1.Container.LabelsEntryR\x06labels\x12/\n" +
	"\x05ports\x18\r \x03(\v2\x19.icc.agent.v1.PortBindingR\x05ports\x124\n" +
	"\x06limits\x18\x0e \x01(\v2\x1c.icc.agent.v1.ResourceLimitsR\x06limits\x12\x19\n" +
	"\benv_hash\x18\x0f \x01(\tR\aenvHash\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\vPortBinding\x12%\n" +
	"\x0econtainer_port\x18\x01 \x01(\rR\rcontainerPort\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x17\n" +
	"\ahost_ip\x18\x03 \x01(\tR\x06hostIp\x12\x1b\n" +
	"\thost_port\x18\x04 \x01(\rR\bhostPort\"G\n" +
	"\x0eResourceLimits\x12\x12\n" +
	"\x04cpus\x18\x01 \x01(\x01R\x04cpus\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x04R\vmemoryBytes\"\xa1\x01\n" +
	"\x0eComposeProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vworking_dir\x18\x02 \x01(\tR\n" +
	"workingDir\x12!\n" +
	"\fconfig_files\x18\x03 \x03(\tR\vconfigFiles\x12\x1b\n" +
	"\tenv_files\x18\x04 \x03(\tR\benvFiles\x12\x1a\n" +
	"\bservices\x18\x05 \x03(\tR\bservicesB\xa0\x01\n" +
	"\x10com.icc.agent.v1B\x0eInventoryProtoP\x01Z*icc/agent/internal/pb/icc/agent/v1;agentv1\xa2\x02\x03IAX\xaa\x02\fIcc.Agent.V1\xca\x02\fIcc\\Agent\\V1\xe2\x02\x18Icc\\Agent\\V1\\GPBMetadata\xea\x02\x0eIcc::Agent::V1b\x06proto3"

var (
	file_icc_agent_v1_inventory_proto_rawDescOnce sync.Once
	file_icc_agent_v1_inventory_proto_rawDescData []byte
)

func file_icc_agent_v1_inventory_proto_rawDescGZIP() []byte {
	file_icc_agent_v1_inventory_proto_rawDescOnce.Do(func() {
		file_icc_agent_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_icc_agent_v1_inventory_proto_rawDesc), len(file_icc_agent_v1_inventory_proto_rawDesc)))
	})
	return file_icc_agent_v1_inventory_proto_rawDescData
}

var file_icc_agent_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_icc_agent_v1_inventory_proto_goTypes = []any{
	(*HostInfo)(nil),              // 0: icc.agent.v1.HostInfo
	(*InventorySnapshot)(nil),     // 1: icc.agent.v1.InventorySnapshot
	(*Container)(nil),             // 2: icc.agent.v1.Container
	(*PortBinding)(nil),           // 3: icc.agent.v1.PortBinding
	(*ResourceLimits)(nil),        // 4: icc.agent.v1.ResourceLimits
	(*ComposeProject)(nil),        // 5: icc.agent.v1.ComposeProject
	nil,                           // 6: icc.agent.v1.Container.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_icc_agent_v1_inventory_proto_depIdxs = []int32{
	7, // 0: icc.agent.v1.InventorySnapshot.collected_at:type_name -> google.protobuf.Timestamp
	0, // 1: icc.agent.v1.InventorySnapshot.host:type_name -> icc.agent.v1.HostInfo
	2, // 2: icc.agent.v1.InventorySnapshot.containers:type_name -> icc.agent.v1.Container
	5, // 3: icc.agent.v1.InventorySnapshot.compose_projects:type_name -> icc.agent.v1.ComposeProject
	7, // 4: icc.agent.v1.Container.created_at:type_name -> google.protobuf.Timestamp
	7, // 5: icc.agent.v1.Container.started_at:type_name -> google.protobuf.Timestamp
	6, // 6: icc.agent.v1.Container.labels:type_name -> icc.agent.v1.Container.LabelsEntry
	3, // 7: icc.agent.v1.Container.ports:type_name -> icc.agent.v1.PortBinding
	4, // 8: icc.agent.v1.Container.limits:type_name -> icc.agent.v1.ResourceLimits
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_icc_agent_v1_inventory_proto_init() }
func file_icc_agent_v1_inventory_proto_init() {
	if File_icc_agent_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_icc_agent_v1_inventory_proto_rawDesc), len(file_icc_agent_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_icc_agent_v1_inventory_proto_goTypes,
		DependencyIndexes: file_icc_agent_v1_inventory_proto_depIdxs,
		MessageInfos:      file_icc_agent_v1_inventory_proto_msgTypes,
	}.Build()
	File_icc_agent_v1_inventory_proto = out.File
	file_icc_agent_v1_inventory_proto_goTypes = nil
	file_icc_agent_v1_inventory_proto_depIdxs = nil
}
