// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: icc/agent/v1/telemetry.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogStream int32

const (
	LogStream_LOG_STREAM_UNSPECIFIED LogStream = 0
	LogStream_LOG_STREAM_STDOUT      LogStream = 1
	LogStream_LOG_STREAM_STDERR      LogStream = 2
)

// Enum value maps for LogStream.
var (
	LogStream_name = map[int32]string{
		0: "LOG_STREAM_UNSPECIFIED",
		1: "LOG_STREAM_STDOUT",
		2: "LOG_STREAM_STDERR",
	}
	LogStream_value = map[string]int32{
		"LOG_STREAM_UNSPECIFIED": 0,
		"LOG_STREAM_STDOUT":      1,
		"LOG_STREAM_STDERR":      2,
	}
)

func (x LogStream) Enum() *LogStream {
	p := new(LogStream)
	*p = x
	return p
}

func (x LogStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogStream) Descriptor() protoreflect.EnumDescriptor {
	return file_icc_agent_v1_telemetry_proto_enumTypes[0].Descriptor()
}

func (LogStream) Type() protoreflect.EnumType {
	return &file_icc_agent_v1_telemetry_proto_enumTypes[0]
}

func (x LogStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogStream.Descriptor instead.
func (LogStream) EnumDescriptor() ([]byte, []int) {
	return file_icc_agent_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

// Пакет метрик в модели Prometheus: имя + метки + значение.
// Центр пересылает их в VictoriaMetrics.
type MetricBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Samples       []*MetricSample        `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricBatch) Reset() {
	*x = MetricBatch{}
	mi := &file_icc_agent_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBatch) ProtoMessage() {}

func (x *MetricBatch) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBatch.ProtoReflect.Descriptor instead.
func (*MetricBatch) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *MetricBatch) GetSamples() []*MetricSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type MetricSample struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Например "container_cpu_usage_ratio", "host_memory_used_bytes".
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSample) Reset() {
	*x = MetricSample{}
	mi := &file_icc_agent_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSample) ProtoMessage() {}

func (x *MetricSample) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSample.ProtoReflect.Descriptor instead.
func (*MetricSample) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *MetricSample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricSample) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricSample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricSample) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Пакет строк логов. Центр пересылает их в VictoriaLogs.
type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_icc_agent_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *LogBatch) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LogEntry struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source    *LogSource             `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Stream    LogStream              `protobuf:"varint,3,opt,name=stream,proto3,enum=icc.agent.v1.LogStream" json:"stream,omitempty"`
	Message   string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Строка была обрезана до max_log_line_bytes.
	Truncated     bool `protobuf:"varint,5,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_icc_agent_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetSource() *LogSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *LogEntry) GetStream() LogStream {
	if x != nil {
		return x.Stream
	}
	return LogStream_LOG_STREAM_UNSPECIFIED
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type LogSource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContainerId    string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ContainerName  string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ComposeProject string                 `protobuf:"bytes,3,opt,name=compose_project,json=composeProject,proto3" json:"compose_project,omitempty"`
	ComposeService string                 `protobuf:"bytes,4,opt,name=compose_service,json=composeService,proto3" json:"compose_service,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogSource) Reset() {
	*x = LogSource{}
	mi := &file_icc_agent_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogSource) ProtoMessage() {}

func (x *LogSource) ProtoReflect() protoreflect.Message {
	mi := &file_icc_agent_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogSource.ProtoReflect.Descriptor instead.
func (*LogSource) Descriptor() ([]byte, []int) {
	return file_icc_agent_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *LogSource) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *LogSource) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *LogSource) GetComposeProject() string {
	if x != nil {
		return x.ComposeProject
	}
	return ""
}

func (x *LogSource) GetComposeService() string {
	if x != nil {
		return x.ComposeService
	}
	return ""
}

var File_icc_agent_v1_telemetry_proto protoreflect.FileDescriptor

const file_icc_agent_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1cicc/agent/v1/telemetry.proto\x12\ficc.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\vMetricBatch\x124\n" +
	"\asamples\x18\x01 \x03(\v2\x1a.icc.agent.v1.MetricSampleR\asamples\"\xed\x01\n" +
	"\fMetricSample\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\x06labels\x18\x02 \x03(\v2&.icc.agent.v1.MetricSample.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\bLogBatch\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.icc.agent.v1.LogEntryR\aentries\"\xde\x01\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12/\n" +
	"\x06source\x18\x02 \x01(\v2\x17.icc.agent.v1.LogSourceR\x06source\x12/\n" +
	"\x06stream\x18\x03 \x01(\x0e2\x17.icc.agent.v1.LogStreamR\x06stream\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttruncated\x18\x05 \x01(\bR\ttruncated\"\xa7\x01\n" +
	"\tLogSource\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12'\n" +
	"\x0fcompose_project\x18\x03 \x01(\tR\x0ecomposeProject\x12'\n" +
	"\x0fcompose_service\x18\x04 \x01(\tR\x0ecomposeService*U\n" +
	"\tLogStream\x12\x1a\n" +
	"\x16LOG_STREAM_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LOG_STREAM_STDOUT\x10\x01\x12\x15\n" +
	"\x11LOG_STREAM_STDERR\x10\x02B\xa0\x01\n" +
	"\x10com.icc.agent.v1B\x0eTelemetryProtoP\x01Z*icc/agent/internal/pb/icc/agent/v1;agentv1\xa2\x02\x03IAX\xaa\x02\fIcc.Agent.V1\xca\x02\fIcc\\Agent\\V1\xe2\x02\x18Icc\\Agent\\V1\\GPBMetadata\xea\x02\x0eIcc::Agent::V1b\x06proto3"

var (
	file_icc_agent_v1_telemetry_proto_rawDescOnce sync.Once
	file_icc_agent_v1_telemetry_proto_rawDescData []byte
)

func file_icc_agent_v1_telemetry_proto_rawDescGZIP() []byte {
	file_icc_agent_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_icc_agent_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_icc_agent_v1_telemetry_proto_rawDesc), len(file_icc_agent_v1_telemetry_proto_rawDesc)))
	})
	return file_icc_agent_v1_telemetry_proto_rawDescData
}

var file_icc_agent_v1_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_icc_agent_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_icc_agent_v1_telemetry_proto_goTypes = []any{
	(LogStream)(0),                // 0: icc.agent.v1.LogStream
	(*MetricBatch)(nil),           // 1: icc.agent.v1.MetricBatch
	(*MetricSample)(nil),          // 2: icc.agent.v1.MetricSample
	(*LogBatch)(nil),              // 3: icc.agent.v1.LogBatch
	(*LogEntry)(nil),              // 4: icc.agent.v1.LogEntry
	(*LogSource)(nil),             // 5: icc.agent.v1.LogSource
	nil,                           // 6: icc.agent.v1.MetricSample.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_icc_agent_v1_telemetry_proto_depIdxs = []int32{
	2, // 0: icc.agent.v1.MetricBatch.samples:type_name -> icc.agent.v1.MetricSample
	6, // 1: icc.agent.v1.MetricSample.labels:type_name -> icc.agent.v1.MetricSample.LabelsEntry
	7, // 2: icc.agent.v1.MetricSample.timestamp:type_name -> google.protobuf.Timestamp
	4, // 3: icc.agent.v1.LogBatch.entries:type_name -> icc.agent.v1.LogEntry
	7, // 4: icc.agent.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	5, // 5: icc.agent.v1.LogEntry.source:type_name -> icc.agent.v1.LogSource
	0, // 6: icc.agent.v1.LogEntry.stream:type_name -> icc.agent.v1.LogStream
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_icc_agent_v1_telemetry_proto_init() }
func file_icc_agent_v1_telemetry_proto_init() {
	if File_icc_agent_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_icc_agent_v1_telemetry_proto_rawDesc), len(file_icc_agent_v1_telemetry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_icc_agent_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_icc_agent_v1_telemetry_proto_depIdxs,
		EnumInfos:         file_icc_agent_v1_telemetry_proto_enumTypes,
		MessageInfos:      file_icc_agent_v1_telemetry_proto_msgTypes,
	}.Build()
	File_icc_agent_v1_telemetry_proto = out.File
	file_icc_agent_v1_telemetry_proto_goTypes = nil
	file_icc_agent_v1_telemetry_proto_depIdxs = nil
}
